language: node_js
sudo: required
services:
  - docker
node_js:
- 6
after_success:
  - npm run coveralls
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t "trademachines/riemann-monitoring" .;
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push trademachines/riemann-monitoring;
    fi
